### ISSUE TITLE
override data source

### ISSUE THREAD

**Issue by pocketmax** [montagejs/collections#103]
Instead of using a native object to store items, you could point the collection to an alternative data source instead. Like a memory store like this one...

http://jxcore.com/docs/jxcore-store.html

```
var List = require("collections/list");
List.source = jxcore.store;
var list = new List([1,2,3]);
```
This way, all the values are stored in the jxcore.store but accessed via the list collection. Almost like an adapter/wrapper pattern.

**Comment by kriskowal** [comment]
Collections provides quite lot of generics that would enable one to create a proxy for a jxcore-store, but providing such an adapter is outside the scope of the collections project, and well within the scope of a small package that depends upon and combines both.
