### ISSUE TITLE
Typescript definition support

### ISSUE THREAD

**Issue by ttony** [montagejs/collections#125]
Hi there,

wanted to check with you if you have plan to support typescript definition files?

-Y

**Comment by Stuk** [comment]
Afraid this isn't on the radar, no.

**Comment by kriskowal** [comment]
I would not be against having them if someone wishes to add and support them. That of course includes ensuring that the implementation tracks the interface with automated tests.

**Comment by hthetiot** [comment]
Duplicate #170
