### ISSUE TITLE
2.0.2 breaks dependent libraries

### ISSUE THREAD

**Issue by AlicanC** [montagejs/collections#132]
[gtor](https://github.com/kriskowal/gtor/) depends on `^2.0.1` which currently resolves to `2.0.2` on npm. Sadly, all "shim*.js" files were removed in 2.0.2 and that breaks gtor (and probably other libraries).

You can see both packages for comparison:
https://registry.npmjs.org/collections/-/collections-2.0.1.tgz
https://registry.npmjs.org/collections/-/collections-2.0.2.tgz

**Comment by kriskowal** [comment]
I’m going to call this a gtor bug.

**Comment by AlicanC** [comment]
Should I open an issue there?

**Comment by kriskowal** [comment]
or a PR
