### ISSUE TITLE
List.sort ignores supplied comparator.

### ISSUE THREAD

**Issue by sunrize531** [montagejs/collections#133]
https://github.com/montagejs/collections/blob/master/list.js#L372

Also it probably can be MUCH faster, using node swaps, especially for large collections, since currently it converting data to array and back.

**Comment by kriskowal** [comment]
Indeed. Since List is far from being an ideal structure for sorting, the current implementation provided is merely provided for completeness. PRs welcome for a less wasteful list sort.

**Comment by sunrize531** [comment]
Well, for 'competeness' it has to pass its arguments to sorted.

Then, it would be nice to implement something like this:
http://www.chiark.greenend.org.uk/~sgtatham/algorithms/listsort.html

I'll see what i can do here in next couple of days.

**Comment by sunrize531** [comment]
Well, for full completeness it *should* pass comparator to sorted.
http://www.chiark.greenend.org.uk/~sgtatham/algorithms/listsort.html

**Comment by hthetiot** [comment]
see #191
