### ISSUE TITLE
Array#find is implemented wrong

### ISSUE THREAD

**Issue by kylehg** [montagejs/collections#139]
Your implementation of `Array.prototype.find()` is wrong — it returns the index of the matching element, not the element itself. See the MDN article on [`.find()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) — you've implemented `.findIndex`.

Relatedly, it's very upsetting that this library doesn't bother to check `Array.prototype` for a native version first before overwriting. This ruins the party for anyone who consumes this library as a node module, even if it's only as a second-order dependency.

**Comment by kriskowal** [comment]
These issues are addressed in version 2 and can be installed via npm
install collections@2. The v1 api is published as latest to avoid breaking
legacy apps.

**Comment by morlay** [comment]
But, why add the wrong `find` back in collections@3?
https://github.com/montagejs/collections/blob/v3.0.0/shim-array.js#L135

**Comment by icfantv** [comment]
@kriskowal, do you have an answer to @morlay's question?  Thanks.

**Comment by kriskowal** [comment]
Collections are managed by Montage Studio. They needed to cut a major version that fixed other things, but retained this old behavior for compatibility with deployed versions in production. So version 2 is still ahead of version 3 in this regard. Montage was not able to use version 2 because I made radical changes to the observer subsystem, factoring it into a library and changing the interface. Montage will not be able to reunite with the changes I made for version 2 until someone upgrades FRB to use version 2 change observers. This is not on my roadmap.

**Comment by kriskowal** [comment]
However, Version 4 could cherry-pick the fixes in version 2 for this feature with minimal impact to Montage applications and without breaking FRB.

**Comment by icfantv** [comment]
ok, thanks. v2 it is.

**Comment by kriskowal** [comment]
For issues and pulls against v2, I maintain v2 as the master branch on my fork https://github.com/kriskowal/collections. Thanks.

**Comment by xjamundx** [comment]
Is there any way we can add a deprecated warning or something on this. It caused a production bug for us as well.

**Comment by kriskowal** [comment]
I think a deprecation warning would be reasonable, a log to console like “Warning: collections v1 monkey-patches the find method in a way inconsistent with the ECMAScript 6 specification.” What the warning suggests you do is the hard part. v2 is not eligible for folks using Montage. v3 does not solve this problem. v2 in fact, no longer monkey-patches Array at all, and instead favors polymorphic functions like `swap(collection, start, minusLength, plus)` from `pop-swap`.

I’ll defer to @marchant to sort out the deprecation and migration story.

**Comment by hthetiot** [comment]
Duplicate #185

**Comment by codebling** [comment]
See also issues #36 #70 #94 #95 #116 #139 #145 #162 #165 #169 #178 #182 #185 #197 #215 #220 and PRs #94 #95 #116 #173 #189 #212. Branch [`v2`](https://github.com/montagejs/collections/tree/v2) fixes these issues by avoiding global object modification.
