### ISSUE TITLE
What happened to browser compatibility?

### ISSUE THREAD

**Issue by TWiStErRob** [montagejs/collections#142]
Is the whole library available as a single .js file to be consumed in browser? (Browserify is not an option, I'm looking for something that doesn't require installing another N tools and increase the build times)

What's going on with `collections*.js` in the root of the repo?
They weren't changed for 3 years, so I guess they should be deleted or the build updated so it updates those at releases.

**Comment by gandhirajan** [comment]
Any resolution on this? Is there any single library file available so that it can be included as is and used in browser? Please respond.

**Comment by hthetiot** [comment]
Look at collections.min.js or use mr to load npm package on browser.

**Comment by TWiStErRob** [comment]
Thanks, been a while, don't even remember which project I wanted this on.
Since then I learned npm, webpack and others, JS ecosystem is nice.
