### ISSUE TITLE
release notes

### ISSUE THREAD

**Issue by lmj0011** [montagejs/collections#166]
Would be helpful to annotate fixes/changes for future releases

https://github.com/montagejs/collections/releases

So the more cautious of us can avoid being slapped in the face with something like this:
https://github.com/montagejs/collections/issues/165

**Comment by hthetiot** [comment]
Yes 2.0.0 never got in change logs I will try to update it.

**Comment by hthetiot** [comment]
https://github.com/montagejs/collections/blob/master/CHANGES.md
