### ISSUE TITLE
Array.find seems to be broken again

### ISSUE THREAD

**Issue by yang** [montagejs/collections#185]
Tested 5.0.7.

**Comment by hthetiot** [comment]
Looking into it.

**Comment by hthetiot** [comment]
@yang Can you try npm install collections@2.0.3 and tell me if that fix your issue.
I'm going to merge v2 branch in master and release v6 soon.

**Comment by hthetiot** [comment]
PR fix https://github.com/montagejs/collections/pull/188

**Comment by hthetiot** [comment]
@yang 

Fixed in collections 5.1.0
- https://github.com/montagejs/collections/tree/v5.1.0
- https://www.npmjs.com/package/collections

For legacy issue notification of release:
cc @Jorenm @codebling @kylehg @xjamundx @kylehg

**Comment by codebling** [comment]
Will check that out, thanks for the cc!

**Comment by codebling** [comment]
#162 is still broken

**Comment by erothmayer** [comment]
This appears to still be a problem (or another breaking change to the base language collections is similarly broken). In 5.1.8 3rd party libraries still have unexpected failures, while going back to 2.0.3 fixes them.

**Comment by codebling** [comment]
See also issues #36 #70 #94 #95 #116 #139 #145 #162 #165 #169 #178 #182 #185 #197 #215 #220 and PRs #94 #95 #116 #173 #189 #212. As mentioned, branch `v2` avoids global object modification and so works.
