### ISSUE TITLE
SortedMap.reduceRight behaviour seems incorrect

### ISSUE THREAD

**Issue by Nipatsku** [montagejs/collections#198]
I have a SortedMap with number keys (0, 1, 2) and corresponding string values.
I'd expect 'reduceRight' to callback in the following key-order: (2, 1, 0) but instead I'm getting (2, 0, 1).
Seems like a problem that people would run into quite frequently.

This is the code I'm testing with
`
import { SortedMap } from 'collections/sorted-map'

const map: SortedMap<number, string> = new SortedMap()
map.set( 0, "element_0" )
map.set( 1, "element_1" )
map.set( 2, "element_2" )

console.log( "\nforEach" )
map.forEach( ( val, key ) => {
    console.log( key + ": " + val )
} )

console.log( "\nreduce" )
map.reduce( ( cur, val, key ) => {
    console.log( key + ": " + val )
    return false
} )

console.log( "\nreduceRight" )
map.reduceRight( ( cur, val, key ) => {
    console.log( key + ": " + val )
    return false
} )
`

**Comment by Nipatsku** [comment]
My console log looks like this:

forEach
0: element_0
1: element_1
2: element_2

reduce
0: element_0
1: element_1
2: element_2

reduceRight
2: element_2
0: element_0
1: element_1

**Comment by hthetiot** [comment]
This is fixed by #206 and released today as part of v5.1.3
- https://github.com/montagejs/collections/blob/master/CHANGES.md#v513

If you still have the issue please re-open @Nipatsku
