### ISSUE TITLE
May I write an article comparing your library "collections"?

### ISSUE THREAD

**Issue by samchon** [montagejs/collections#199]
Nice to meet you. I'm a developer of [**TSTL**](https://github.com/samchon/tstl), which is an migration project of C++ STL (Standard Template Library) to TypeScript. Traveling similar libraries like mine, I found this awesome repository.

TSTL provides 4 modules (containers, iterators, algorithms and functors) and in the container module, many features are seemed like similar with you. To announce my library to the world and be famous like you, I'm planning to make a PR homepage and put an article comparing my library (TSTL) with others. The article will concentrate on which features are supported and which are not. The comparison would be represented by table.

  - The table will be seemed like this: https://gist.github.com/samchon/e3009c9a5685e295dfff24b48b80d2c5

Before writing the article, I think I should get permission from the origin developers of the compared libraries. May I write the article including your library? If you don't want, then I will not include yours.

**Comment by Deilan** [comment]
@samchon It's [licensed](https://github.com/montagejs/collections/blob/master/LICENSE.md) under 3-clause BSD license, so why not? :)

**Comment by hthetiot** [comment]
@samchon Not problem collections is only maintained but not actively developed this days.

For a better reference implementation I would also pick at this: 
- https://github.com/montagejs/collections/pull/189
