### ISSUE TITLE
Set.reduceRight seems to be incorrect.

### ISSUE THREAD

**Issue by Nikolsi** [montagejs/collections#210]
Set.reduceRight did not callback at all. It was caused by not using the reverseOrder array and incorrect index counting.

I have created a pull request #209 with fix for it

**Comment by Nikolsi** [comment]
Does anybody here? :D

**Comment by marchant** [comment]
Thanks @Nikolsi for the nudge and providing the patch, just merged, sorry for the delay!

**Comment by Nikolsi** [comment]
@marchant Thank you for accepting the merge request 👍
