### ISSUE TITLE
Must you modify core prototypes? e.g. Object.prototype

### ISSUE THREAD

**Issue by buchanae** [montagejs/collections#70]
I notice you "shim" a bunch of things onto core prototypes, e.g. Object.addEach.  Is that really necessary? Isn't it taboo to modify Object.prototype?

Can you at least point me to the ECMAScript standard that is planning to implement Object.addEach and all its friends? I can't find it.

I want to use your library, but honestly I get a bad feeling about all this modification of core prototypes.

**Comment by timruffles** [comment]
I think it'd be at least good to document this. It's definitely a "principle of least surprise" violation (e.g I was very confused by seeing `[].set()` in the source) considering the JS ecosystem aversion to extending core types.
